# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customerbankaccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbankaccount',
            name='Relationship',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='registercustomer',
            name='Relationship',
            field=models.CharField(default='', max_length=200),
        ),
    ]
