# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180419_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercustomertranscations',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
