# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_registercustomertranscations_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registercustomer',
            name='Image',
        ),
    ]
