# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-23 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_registercustomer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerbankaccount',
            old_name='Account_number',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='customerbankaccount',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='customerbankaccount',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customerbankaccount',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='customerbankaccount',
            old_name='Identification_information',
            new_name='identification_information',
        ),
        migrations.RenameField(
            model_name='customerbankaccount',
            old_name='Next_of_kin',
            new_name='next_of_kin',
        ),
        migrations.RenameField(
            model_name='customerbankaccount',
            old_name='Relationship',
            new_name='relationship',
        ),
        migrations.RenameField(
            model_name='customerbankaccount',
            old_name='Residence',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='customerbankaccount',
            old_name='Work_history',
            new_name='work_history',
        ),
        migrations.RenameField(
            model_name='registercustomer',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='registercustomer',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='registercustomer',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='registercustomer',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='registercustomer',
            old_name='Next_of_kin',
            new_name='next_of_kin',
        ),
        migrations.RenameField(
            model_name='registercustomer',
            old_name='Occupation',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='registercustomer',
            old_name='Residence',
            new_name='relationship',
        ),
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='Account_number',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='Transcation_date',
            new_name='transcation_date',
        ),
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='Transcation_type',
            new_name='transcation_type',
        ),
        migrations.AddField(
            model_name='registercustomer',
            name='residence',
            field=models.CharField(default='', max_length=200),
        ),
    ]
