# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-23 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180423_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registercustomer',
            name='Relationship',
        ),
    ]
