# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-23 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_registercustomer_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='transcation_date',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='transcation_type',
            new_name='transaction_type',
        ),
    ]
