# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-23 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180423_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='Account_number',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='Transaction_date',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='registercustomertranscations',
            old_name='Transaction_type',
            new_name='transaction_type',
        ),
    ]
